### ISSUE TITLE
CIGAR related error in read simulations

### ISSUE THREAD

**Issue by ju-mu** [zstephens/neat-genreads#59] opened 2019-04-11 09:14 UTC
Hi, 

after your fix to #56 I have encountered CIGAR related errors as described in #58.
After that, commit 7548702 seemed to have fixed the issue for a test capture seq dataset with 200X.

Unfortunately I just ran a 1000X simulation spread to about 30 jobs and I have encountered the same error for a few jobs:

`Index error when attempting to find cigar string.
23865 23866
(23656, 23866)
0 360 331`

`Index error when attempting to find cigar string.
23870 23870
(23740, 23870)
1 280 267`

`Index error when attempting to find cigar string.
23859 23859
(23796, 23859)
0 213 204`

`Index error when attempting to find cigar string.
23860 23861
(23816, 23861)
0 195 186`

`Index error when attempting to find cigar string.
23871 23872
(23809, 23872)
0 213 204`

`Index error when attempting to find cigar string.
23869 23869
(23764, 23869)
1 255 244`

`Index error when attempting to find cigar string.
46520 46520
(46437, 46520)
0 233 223`

`Index error when attempting to find cigar string.
23880 23880
(23670, 23880)
0 360 331`

`Index error when attempting to find cigar string.
23875 23875
(23665, 23875)
0 360 331`

`Index error when attempting to find cigar string.
23865 23865
(23761, 23865)
1 254 244`

`Index error when attempting to find cigar string.
23864 23864
(23801, 23864)
1 213 204`

`Index error when attempting to find cigar string.
23880 23880
(23870, 23880)
0 160 151`

`Index error when attempting to find cigar string.
23976 23977
(23914, 23977)
1 213 204`

`Index error when attempting to find cigar string.
23858 23858
(23814, 23858)
1 194 186`

I have used similar settings as before:
`python genReads.py -r test.fa -R 150 -c 1000 -o testdir/testprefix --vcf -t agilent_v7.bed -e tumor_errorModel.p -m tumor_MutModel.p --pe-model tumor_fraglen.p --gc-model tumor_gcBiasModel.p --bam --rng 999 --gz --job 1 32`

Errors occurred in almost 50% of the jobs. In another instance using just a slightly different bed file, errors occurred only in 2 jobs.

Many thanks!

**Comment by dinggens** [comment] 2019-06-07 07:27
Hello,

I encounter the same error on several runs.
Is there any solution meanwhile?

Many thanks in advance!

**Comment by ju-mu** [comment] 2019-06-07 11:42
Unfortunately there are no versioned releases, but my solution is to use the neat version before commits on Mar 13, 2019.
Do note that the bam file contains a lot of artifacts around indel sites in this version though. golden fastq and vcf files seem accurate according to my tests.

**Comment by zstephens** [comment] 2019-06-07 18:28
Sorry for the delay, I had been meaning to revisit this but it was proving difficult in my initial debugging because I was unable to replicate the error on a small-scale test run.

I have narrowed the issue down to the section of code dealing with sampling coordinates for paired-end fragments. The distribution being sampled from seems to include more coordinates than it should, allowing the selection of read positions beyond the bounds of the current reference window being processed (thus causing index errors).

I'm wary about making changes whilst unable to reproduce the crash on my end. Would it be possible for you to share the tumor_fraglen.p file with me?

**Comment by zstephens** [comment] 2019-06-07 21:19
In the meantime I pushed a change that _might_ have fixed this. I added some extra checks around the coordinate sampling.

**Comment by ju-mu** [comment] 2019-06-07 22:37
Great thanks! 
[This is one of the fraglen.p files I have used.](http://pc.cd/MesctalK )

**Comment by dinggens** [comment] 2019-06-13 14:02
Thanks a lot!
For me, the error did not occur again!

**Comment by ju-mu** [comment] 2019-06-13 15:46
Same here. So far I have not observed the error with the most recent version.

**Comment by zstephens** [comment] 2019-06-13 15:48
Great to hear! Closing this for now.

**Closed by zstephens** 2019-06-13 15:48 UTC
